# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
#  USE_BSPM="true"

warnings_are_errors: true

#before_install:
#  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install libglpk-dev

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
 exclude:
    - r:  devel
      os: osx
    - r:  oldrel
      os: osx


r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
